
POST https://sleepy-puce-greyhound.cyclic.app/products
Content-Type: application/json

  {
    "id": 10150,
    "category": "Sarees",
    "name": "WETLESS RAINBOW ZARI",
    "original_price": 4156,
    "discounted_price": 316,
    "sizes": [
      "Free Size"
    ],
    "images": [
      "https://images.meesho.com/images/products/72024275/9cvk9_512.jpg",
      "https://images.meesho.com/images/products/72349131/ndz0q_512.jpg",
     
      "https://images.meesho.com/images/products/72349131/9dvpk_512.jpg"
    ],
    "details": {
      "Fabric": "Chiffon",
      "Pattern": "Self Design",
      "Multipack": "Single",
      "Description": "Best qaualtiy "
    },
    "seller_id": 1
  }
###
POST https://sleepy-puce-greyhound.cyclic.app/user/login
Content-Type: application/json
method:POST 
  {
    "username":"admin",
    "password":"admin"
  }


